# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
