# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160614_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars'),
        ),
    ]
