# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import stats.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, upload_to=stats.models.get_avatar_path),
        ),
    ]
