# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20160617_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestedstats',
            name='common_teammates',
            field=models.CharField(default='', max_length=80),
        ),
    ]
